# Generated by Django 4.0.3 on 2022-11-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
    ]
