# Generated by Django 4.0.3 on 2022-11-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_sub_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sub_1',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='student.subject'),
        ),
    ]
