# Generated by Django 4.0.3 on 2022-11-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_sub_1_student_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
