# Generated by Django 4.0.3 on 2022-11-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
