# Generated by Django 4.0.3 on 2022-11-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(to='student.subject'),
        ),
    ]
