# Generated by Django 4.0.3 on 2022-11-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_topic', models.CharField(max_length=50)),
                ('exam_grade', models.IntegerField()),
                ('confidence_level', models.IntegerField()),
                ('knowledge_level', models.IntegerField()),
                ('feedback_from_teacher', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Target_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_grade', models.CharField(choices=[('80%', 'A*'), ('70%', 'A'), ('60%', 'B'), ('50%', 'C'), ('40%', 'D'), ('30%', 'E')], max_length=4)),
                ('target_grade', models.CharField(blank=True, choices=[('80%', 'A*'), ('70%', 'A'), ('60%', 'B'), ('50%', 'C'), ('40%', 'D'), ('30%', 'E')], max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
