# Generated by Django 4.0.3 on 2022-11-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_subject_id_subject_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='student_id',
            new_name='subject_id',
        ),
    ]
