# Generated by Django 4.0.3 on 2022-11-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_student_id_subject_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('studentData_id', models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('name_of_topic', models.CharField(max_length=50)),
                ('exam_grade', models.IntegerField()),
                ('confidence_level', models.IntegerField()),
                ('knowledge_level', models.IntegerField()),
                ('feedback_from_teacher', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name_of_topic',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='exam_grade',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='feedback_from_teacher',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='knowledge_level',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='student',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='subTopicData',
            fields=[
                ('subTopicData_id', models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('subtopic', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')])),
                ('studentdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='subTopic',
            fields=[
                ('subTopic_id', models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.topic')),
            ],
        ),
        migrations.AddField(
            model_name='studentdata',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.topic'),
        ),
    ]
