# Generated by Django 4.0.3 on 2022-11-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentdata_rename_name_of_topic_topic_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
        ),
    ]
