# Generated by Django 4.0.3 on 2022-11-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_topic_subject_studentdata_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='name_of_topic',
        ),
    ]
